name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC to fetch fresh data
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.127.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cache processed data and cache files
        uses: actions/cache@v4
        with:
          path: |
            data/stations.json
            cache/
          key: fkbb-data-${{ github.run_number }}
          restore-keys: |
            fkbb-data-
        
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
          
      - name: Install Python and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pandas requests beautifulsoup4 tqdm lxml
          
      - name: Fetch and process Bluebike data
        run: |
          # Create directories that might not exist in fresh checkout
          mkdir -p data cache/zip cache/csv
          # Run with timeout and better error handling
          timeout 30m python scripts/process_data.py || {
            echo "Data processing failed or timed out. Creating minimal site structure..."
            # Create minimal data structure if processing fails
            echo '{"metadata":{"processed_months":[],"last_updated":"'"$(date -u +"%Y-%m-%d %H:%M:%S UTC")"'","total_stations":0},"station_registry":{},"station_pairs":{}}' > data/stations.json
            mkdir -p content/stations
            echo "---" > content/_index.md
            echo 'title: "FKBB Tracker"' >> content/_index.md
            echo "---" >> content/_index.md
            echo "" >> content/_index.md
            echo "# Fastest Known BlueBike Times" >> content/_index.md
            echo "" >> content/_index.md
            echo "Data processing is currently in progress. Please check back later." >> content/_index.md
          }
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
            
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4